
#ifndef SV4GUIMODULECOMMON_EXPORT_H
#define SV4GUIMODULECOMMON_EXPORT_H

#ifdef _SIMVASCULAR_MODULE_COMMON_STATIC_DEFINE
#  define SV4GUIMODULECOMMON_EXPORT
#  define SV4GUIMODULECOMMON_NO_EXPORT
#else
#  ifndef SV4GUIMODULECOMMON_EXPORT
#    ifdef _simvascular_module_common_EXPORTS
        /* We are building this library */
#      define SV4GUIMODULECOMMON_EXPORT __attribute__((visibility("default")))
#    else
        /* We are using this library */
#      define SV4GUIMODULECOMMON_EXPORT __attribute__((visibility("default")))
#    endif
#  endif

#  ifndef SV4GUIMODULECOMMON_NO_EXPORT
#    define SV4GUIMODULECOMMON_NO_EXPORT __attribute__((visibility("hidden")))
#  endif
#endif

#ifndef SV4GUIMODULECOMMON_DEPRECATED
#  define SV4GUIMODULECOMMON_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef SV4GUIMODULECOMMON_DEPRECATED_EXPORT
#  define SV4GUIMODULECOMMON_DEPRECATED_EXPORT SV4GUIMODULECOMMON_EXPORT SV4GUIMODULECOMMON_DEPRECATED
#endif

#ifndef SV4GUIMODULECOMMON_DEPRECATED_NO_EXPORT
#  define SV4GUIMODULECOMMON_DEPRECATED_NO_EXPORT SV4GUIMODULECOMMON_NO_EXPORT SV4GUIMODULECOMMON_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef SV4GUIMODULECOMMON_NO_DEPRECATED
#    define SV4GUIMODULECOMMON_NO_DEPRECATED
#  endif
#endif

#endif
