
#ifndef SV4GUIMODULEROMSIMULATION_EXPORT_H
#define SV4GUIMODULEROMSIMULATION_EXPORT_H

#ifdef _SIMVASCULAR_MODULE_ROM_SIMULATION_STATIC_DEFINE
#  define SV4GUIMODULEROMSIMULATION_EXPORT
#  define SV4GUIMODULEROMSIMULATION_NO_EXPORT
#else
#  ifndef SV4GUIMODULEROMSIMULATION_EXPORT
#    ifdef _simvascular_module_rom_simulation_EXPORTS
        /* We are building this library */
#      define SV4GUIMODULEROMSIMULATION_EXPORT __attribute__((visibility("default")))
#    else
        /* We are using this library */
#      define SV4GUIMODULEROMSIMULATION_EXPORT __attribute__((visibility("default")))
#    endif
#  endif

#  ifndef SV4GUIMODULEROMSIMULATION_NO_EXPORT
#    define SV4GUIMODULEROMSIMULATION_NO_EXPORT __attribute__((visibility("hidden")))
#  endif
#endif

#ifndef SV4GUIMODULEROMSIMULATION_DEPRECATED
#  define SV4GUIMODULEROMSIMULATION_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef SV4GUIMODULEROMSIMULATION_DEPRECATED_EXPORT
#  define SV4GUIMODULEROMSIMULATION_DEPRECATED_EXPORT SV4GUIMODULEROMSIMULATION_EXPORT SV4GUIMODULEROMSIMULATION_DEPRECATED
#endif

#ifndef SV4GUIMODULEROMSIMULATION_DEPRECATED_NO_EXPORT
#  define SV4GUIMODULEROMSIMULATION_DEPRECATED_NO_EXPORT SV4GUIMODULEROMSIMULATION_NO_EXPORT SV4GUIMODULEROMSIMULATION_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef SV4GUIMODULEROMSIMULATION_NO_DEPRECATED
#    define SV4GUIMODULEROMSIMULATION_NO_DEPRECATED
#  endif
#endif

#endif
