
#ifndef SV4GUIMODULESEGMENTATION_EXPORT_H
#define SV4GUIMODULESEGMENTATION_EXPORT_H

#ifdef _SIMVASCULAR_MODULE_SEGMENTATION_STATIC_DEFINE
#  define SV4GUIMODULESEGMENTATION_EXPORT
#  define SV4GUIMODULESEGMENTATION_NO_EXPORT
#else
#  ifndef SV4GUIMODULESEGMENTATION_EXPORT
#    ifdef _simvascular_module_segmentation_EXPORTS
        /* We are building this library */
#      define SV4GUIMODULESEGMENTATION_EXPORT __attribute__((visibility("default")))
#    else
        /* We are using this library */
#      define SV4GUIMODULESEGMENTATION_EXPORT __attribute__((visibility("default")))
#    endif
#  endif

#  ifndef SV4GUIMODULESEGMENTATION_NO_EXPORT
#    define SV4GUIMODULESEGMENTATION_NO_EXPORT __attribute__((visibility("hidden")))
#  endif
#endif

#ifndef SV4GUIMODULESEGMENTATION_DEPRECATED
#  define SV4GUIMODULESEGMENTATION_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef SV4GUIMODULESEGMENTATION_DEPRECATED_EXPORT
#  define SV4GUIMODULESEGMENTATION_DEPRECATED_EXPORT SV4GUIMODULESEGMENTATION_EXPORT SV4GUIMODULESEGMENTATION_DEPRECATED
#endif

#ifndef SV4GUIMODULESEGMENTATION_DEPRECATED_NO_EXPORT
#  define SV4GUIMODULESEGMENTATION_DEPRECATED_NO_EXPORT SV4GUIMODULESEGMENTATION_NO_EXPORT SV4GUIMODULESEGMENTATION_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef SV4GUIMODULESEGMENTATION_NO_DEPRECATED
#    define SV4GUIMODULESEGMENTATION_NO_DEPRECATED
#  endif
#endif

#endif
