
#ifndef SV4GUIMODULEMODELOCCT_EXPORT_H
#define SV4GUIMODULEMODELOCCT_EXPORT_H

#ifdef _SIMVASCULAR_MODULE_MODEL_OCCT_STATIC_DEFINE
#  define SV4GUIMODULEMODELOCCT_EXPORT
#  define SV4GUIMODULEMODELOCCT_NO_EXPORT
#else
#  ifndef SV4GUIMODULEMODELOCCT_EXPORT
#    ifdef _simvascular_module_model_occt_EXPORTS
        /* We are building this library */
#      define SV4GUIMODULEMODELOCCT_EXPORT __attribute__((visibility("default")))
#    else
        /* We are using this library */
#      define SV4GUIMODULEMODELOCCT_EXPORT __attribute__((visibility("default")))
#    endif
#  endif

#  ifndef SV4GUIMODULEMODELOCCT_NO_EXPORT
#    define SV4GUIMODULEMODELOCCT_NO_EXPORT __attribute__((visibility("hidden")))
#  endif
#endif

#ifndef SV4GUIMODULEMODELOCCT_DEPRECATED
#  define SV4GUIMODULEMODELOCCT_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef SV4GUIMODULEMODELOCCT_DEPRECATED_EXPORT
#  define SV4GUIMODULEMODELOCCT_DEPRECATED_EXPORT SV4GUIMODULEMODELOCCT_EXPORT SV4GUIMODULEMODELOCCT_DEPRECATED
#endif

#ifndef SV4GUIMODULEMODELOCCT_DEPRECATED_NO_EXPORT
#  define SV4GUIMODULEMODELOCCT_DEPRECATED_NO_EXPORT SV4GUIMODULEMODELOCCT_NO_EXPORT SV4GUIMODULEMODELOCCT_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef SV4GUIMODULEMODELOCCT_NO_DEPRECATED
#    define SV4GUIMODULEMODELOCCT_NO_DEPRECATED
#  endif
#endif

#endif
