
#ifndef SV4GUIMODULESIMULATION_EXPORT_H
#define SV4GUIMODULESIMULATION_EXPORT_H

#ifdef _SIMVASCULAR_MODULE_SIMULATION_STATIC_DEFINE
#  define SV4GUIMODULESIMULATION_EXPORT
#  define SV4GUIMODULESIMULATION_NO_EXPORT
#else
#  ifndef SV4GUIMODULESIMULATION_EXPORT
#    ifdef _simvascular_module_simulation_EXPORTS
        /* We are building this library */
#      define SV4GUIMODULESIMULATION_EXPORT __attribute__((visibility("default")))
#    else
        /* We are using this library */
#      define SV4GUIMODULESIMULATION_EXPORT __attribute__((visibility("default")))
#    endif
#  endif

#  ifndef SV4GUIMODULESIMULATION_NO_EXPORT
#    define SV4GUIMODULESIMULATION_NO_EXPORT __attribute__((visibility("hidden")))
#  endif
#endif

#ifndef SV4GUIMODULESIMULATION_DEPRECATED
#  define SV4GUIMODULESIMULATION_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef SV4GUIMODULESIMULATION_DEPRECATED_EXPORT
#  define SV4GUIMODULESIMULATION_DEPRECATED_EXPORT SV4GUIMODULESIMULATION_EXPORT SV4GUIMODULESIMULATION_DEPRECATED
#endif

#ifndef SV4GUIMODULESIMULATION_DEPRECATED_NO_EXPORT
#  define SV4GUIMODULESIMULATION_DEPRECATED_NO_EXPORT SV4GUIMODULESIMULATION_NO_EXPORT SV4GUIMODULESIMULATION_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef SV4GUIMODULESIMULATION_NO_DEPRECATED
#    define SV4GUIMODULESIMULATION_NO_DEPRECATED
#  endif
#endif

#endif
