
#ifndef SV4GUIMODULEIMAGEPROCESSING_EXPORT_H
#define SV4GUIMODULEIMAGEPROCESSING_EXPORT_H

#ifdef _SIMVASCULAR_MODULE_IMAGEPROCESSING_STATIC_DEFINE
#  define SV4GUIMODULEIMAGEPROCESSING_EXPORT
#  define SV4GUIMODULEIMAGEPROCESSING_NO_EXPORT
#else
#  ifndef SV4GUIMODULEIMAGEPROCESSING_EXPORT
#    ifdef _simvascular_module_imageprocessing_EXPORTS
        /* We are building this library */
#      define SV4GUIMODULEIMAGEPROCESSING_EXPORT __attribute__((visibility("default")))
#    else
        /* We are using this library */
#      define SV4GUIMODULEIMAGEPROCESSING_EXPORT __attribute__((visibility("default")))
#    endif
#  endif

#  ifndef SV4GUIMODULEIMAGEPROCESSING_NO_EXPORT
#    define SV4GUIMODULEIMAGEPROCESSING_NO_EXPORT __attribute__((visibility("hidden")))
#  endif
#endif

#ifndef SV4GUIMODULEIMAGEPROCESSING_DEPRECATED
#  define SV4GUIMODULEIMAGEPROCESSING_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef SV4GUIMODULEIMAGEPROCESSING_DEPRECATED_EXPORT
#  define SV4GUIMODULEIMAGEPROCESSING_DEPRECATED_EXPORT SV4GUIMODULEIMAGEPROCESSING_EXPORT SV4GUIMODULEIMAGEPROCESSING_DEPRECATED
#endif

#ifndef SV4GUIMODULEIMAGEPROCESSING_DEPRECATED_NO_EXPORT
#  define SV4GUIMODULEIMAGEPROCESSING_DEPRECATED_NO_EXPORT SV4GUIMODULEIMAGEPROCESSING_NO_EXPORT SV4GUIMODULEIMAGEPROCESSING_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef SV4GUIMODULEIMAGEPROCESSING_NO_DEPRECATED
#    define SV4GUIMODULEIMAGEPROCESSING_NO_DEPRECATED
#  endif
#endif

#endif
